### ISSUE TITLE
tower always sigsegv and panic

### ISSUE THREAD

**Issue by rj-zhaoxinxing** [kubesphere/tower#28]
## Problem:
Tower is panic and agent connect lost.
<img width="816" alt="image" src="https://user-images.githubusercontent.com/50042167/98947583-6189a280-2530-11eb-97cb-587fc0df6b67.png">

## Toplogy:
Host KS-- Tower(Public Internet) <--------Agent(Internal network)---K8S/KS

## Tower Log
Seemed to Recv error payload and Sig Segment Error
<img width="771" alt="image" src="https://user-images.githubusercontent.com/50042167/98947834-a8779800-2530-11eb-9587-03ec1d6d0450.png">

always output proxy error
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/50042167/98947728-88e06f80-2530-11eb-9460-e8378cefbb11.png">

## Agent Log
<img width="919" alt="image" src="https://user-images.githubusercontent.com/50042167/98947522-4c147880-2530-11eb-8303-0dacc505968e.png">

**Comment by zryfish** [comment]
Could you execute the following command 
```
kubectl -n kubesphere-system logs [tower-pod-name]
```
to get the full logs of the container, and paste it here ?

**Comment by XinxingZh** [comment]
/ # kubectl logs tower-7668df8696-gjqql -n kubesphere-system
I1112 12:27:54.864227       1 options.go:46] CA set to "/ca.crt".
I1112 12:27:54.864290       1 options.go:47] CA key file set to "/ca.key".
I1112 12:27:54.864296       1 options.go:48] Host set to 0.0.0.0
I1112 12:27:54.864300       1 options.go:49] Agent port set to 8080.
I1112 12:27:54.864304       1 options.go:50] Kubeconfig set to "".
I1112 12:27:54.864308       1 options.go:51] Leader election set to false
W1112 12:27:54.864652       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This mightnot work.
I1112 12:27:54.977494       1 proxy.go:234] Listening on 0.0.0.0:8080...
I1112 12:27:57.068200       1 proxy.go:205] Connection established with cluster-a
I1112 12:27:57.373382       1 proxy.go:205] Connection established with cluster-b
I1112 12:27:57.973635       1 proxy.go:205] Connection established with cluster-c
I1112 12:27:58.364305       1 proxy.go:205] Connection established with cluster-d
I1112 12:28:01.065250       1 proxy.go:205] Connection established with cluster-e
I1112 12:28:03.164617       1 proxy.go:205] Connection established with cluster-f
2020/11/12 12:55:40 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:53 http: proxy error: context canceled

**Comment by rj-zhaoxinxing** [comment]
/ # kubectl logs tower-7668df8696-gjqql -n kubesphere-system
I1112 12:27:54.864227       1 options.go:46] CA set to "/ca.crt".
I1112 12:27:54.864290       1 options.go:47] CA key file set to "/ca.key".
I1112 12:27:54.864296       1 options.go:48] Host set to 0.0.0.0
I1112 12:27:54.864300       1 options.go:49] Agent port set to 8080.
I1112 12:27:54.864304       1 options.go:50] Kubeconfig set to "".
I1112 12:27:54.864308       1 options.go:51] Leader election set to false
W1112 12:27:54.864652       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This mightnot work.
I1112 12:27:54.977494       1 proxy.go:234] Listening on 0.0.0.0:8080...
I1112 12:27:57.068200       1 proxy.go:205] Connection established with cluster-a
I1112 12:27:57.373382       1 proxy.go:205] Connection established with cluster-b
I1112 12:27:57.973635       1 proxy.go:205] Connection established with cluster-c
I1112 12:27:58.364305       1 proxy.go:205] Connection established with cluster-d
I1112 12:28:01.065250       1 proxy.go:205] Connection established with cluster-e
I1112 12:28:03.164617       1 proxy.go:205] Connection established with cluster-f
2020/11/12 12:55:40 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:47 http: proxy error: context canceled
2020/11/12 12:55:53 http: proxy error: context canceled

**Comment by zryfish** [comment]
Thanks for the feedback, working on it

**Comment by rj-zhaoxinxing** [comment]
how's the progress ?  thanx

**Comment by devinleee** [comment]
> how's the progress ? thanx

Still working on it.

**Comment by devinleee** [comment]
@XinxingZh Unfortunately I couldn't reproduce this error. Please leave a comment here if you can find a way to reproduce the bug.
