### ISSUE TITLE
Feat: support proxy server and proxy agent highly available.

### ISSUE THREAD

**Issue by devinleee** [kubesphere/tower#31]
Proxy(at least two replications):
Add leader election and kubernetes readiness probe. They both make sure that there are only one proxy running and one endpoint behind the svc. Once one proxy replication is down, another one can start quickly.
Agent(at least two replications):
Add leader election to make sure that there is only one agent running, once one agent replication is down, another one can become the leader quickly.

**Comment by yuswift** [comment]
/close
cause we have merged #33

**Comment by devinleee** [comment]
cause we have merged #33
